/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_SensorsMeter
#define HEADER_SensorsMeter
/*
htop - SensorsMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int SensorsMeter_attributes[];

extern MeterClass SensorsMeter_class;

#endif
